use actix_web::error;
use deadpool_postgres::PoolError;

#[derive(failure::Fail, Debug)]
pub enum Error {
    #[fail(display = "An internal error occured. Please try again later.")]
    PoolError(PoolError),
}

impl From<PoolError> for Error {
    fn from(error: PoolError) -> Self {
        Self::PoolError(error)
    }
}

impl error::ResponseError for Error {}
